In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
A="안녕하세요 지금은 데이터 전처리 수업 시간입니다."
print(A[0])
print(A[:5])
print(A[5:])
print(A[10:14])
print(A[-4])

안
안녕하세요
 지금은 데이터 전처리 수업 시간입니다.
데이터 
입


In [12]:
print("안녕하세요\n반갑습니다")

안녕하세요
반갑습니다


In [18]:
A="안녕 {}" # 타깃에 중괄호 필수
B="반가워"
print(A.format(B))

안녕 반가워


In [16]:
name = "John"
age = 30
print("My name is {} and I'm {} years old.".format(name, age))

My name is John and I'm 30 years old.


In [25]:
A=[10,20,30,40,50,60,70,80,90]
print(A[0]+A[5])

70


In [19]:
A = ["독고영재, 50", "김철수, 30"]
print(A[0])
print(A[0][0:4])

독고영재, 50
독고영재


In [51]:
a=["독고영재, 50", "김철수, 30"]
b=["김철수, 20", "김영희, 25"]

print(a[0][:a[0].index(",")]) # 를 탐지해서 파싱

4
독고영재


In [52]:
#====

In [57]:
a=np.array([1,2,3,4,5])
print(a)
b=np.append(a,[6,7])
print(b)
c=np.insert(a,1,[6,7]) # 1번 칸에 입력
print(c)

[1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 6 7 2 3 4 5]


In [59]:
d=np.delete(a,[1,3]) # 1번 칸 3번칸 삭제
print(d)

[1 3 5]


In [60]:
print(a[a!=4])

[1 2 3 5]


In [61]:
# 수직합

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
merged_array = np.vstack((array1, array2))
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
# 수평합

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
merged_array = np.hstack((array1, array2))
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#==== 딕셔너리

In [64]:
D = [{"name":"독고영재", "age":50},{"name":"김철수", "age":30}]
print(D[0]["name"])
print(D[0]["age"])

독고영재
50


In [67]:
A={1:"김철수", 20:"박영희"}
print(A[1])
c=A[1]
print(c)
d=A.get(1)
print(d)

김철수
김철수
김철수
